In [156]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [157]:
df=pd.read_csv('Titanic-Dataset.csv')
df

PassengerId  Survived  Pclass  \
0              1         0     3.0   
1              2         1     1.0   
2              3         1     3.0   
3              4         1     1.0   
4              5         0     3.0   
..           ...       ...     ...   
886          887         0     2.0   
887          888         1     1.0   
888          889         0     3.0   
889          890         1     1.0   
890          891         0     3.0   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [158]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0     3.0   
1            2         1     1.0   
2            3         1     3.0   
3            4         1     1.0   
4            5         0     3.0   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [159]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0     2.0                     Montvila, Rev. Juozas   
887          888         1     1.0              Graham, Miss. Margaret Edith   
888          889         0     3.0  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1     1.0                     Behr, Mr. Karl Howell   
890          891         0     3.0                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [160]:
df.shape

(891, 12)

In [161]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [162]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [163]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           5
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

1.	What is the survival rate for males vs. females?


In [165]:
q1=df[['Sex','Survived']].groupby('Sex',as_index=False).mean().sort_values(by='Survived',ascending=False)
q1

Sex  Survived
0  female  0.742038
1    male  0.188908

1) Ans: Femal survival rate is 0.74 compared to male survival rate of 0.18, this shows about 75% of survived are women.

2.	Did passengers in higher classes (1st class) have a higher survival rate compared to lower classes (3rd class)?

In [166]:
q2=df[['Pclass','Survived']].groupby('Pclass',as_index=False).mean().sort_values(by='Survived',ascending=False)
q2

Pclass  Survived
0     1.0  0.629630
1     2.0  0.472826
2     3.0  0.242798

2) Ans: Yes, passengers in higher classes(63%) survived more than lower classes(24%).

3.	Did passengers with more family members (siblings/spouses or parents/children) aboard have a higher or lower chance of survival?

In [167]:
q3=df[['SibSp','Survived']].groupby('SibSp',as_index=False).mean().sort_values(by='Survived',ascending=False)
q3

SibSp  Survived
1      1  0.535885
2      2  0.464286
0      0  0.345395
3      3  0.250000
4      4  0.166667
5      5  0.000000
6      8  0.000000

In [168]:
q31=df[['Parch','Survived']].groupby('Parch',as_index=False).mean().sort_values(by='Survived',ascending=False)
q31

Parch  Survived
3      3  0.600000
1      1  0.550847
2      2  0.500000
0      0  0.343658
5      5  0.200000
4      4  0.000000
6      6  0.000000

3) Ans: From the above observation, we can see that passengers with more number of siblings/spouses were less likely to survive with 'SIbSp'= 5,8 having 0 chance of survival.
The same applies for passengers having parents/childrens, with greather number like 4 and 6 having 0 survived.
So, passengers with more family memebers were less likely to survive.

4.	Did the port of embarkation (C, Q, S) influence the survival rate?

In [169]:
q4=df[['Embarked','Survived']].groupby('Embarked',as_index=False).mean().sort_values(by='Survived',ascending=False)
q4

Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957

5.	Did passengers who paid higher fares have a better chance of survival?

In [170]:
q5=df[['Fare','Survived']].groupby('Fare',as_index=False).mean().sort_values(by='Fare',ascending=False)
q5

Fare  Survived
247  512.3292  1.000000
246  263.0000  0.500000
245  262.3750  1.000000
244  247.5208  0.500000
243  227.5250  0.750000
..        ...       ...
4      6.4375  0.000000
3      6.2375  0.000000
2      5.0000  0.000000
1      4.0125  0.000000
0      0.0000  0.066667

[248 rows x 2 columns]

In [171]:
df.corr(numeric_only=True)

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.027613  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338147 -0.077221 -0.035322  0.081629   
Pclass         -0.027613 -0.338147  1.000000 -0.369308  0.083814  0.015178   
Age             0.036847 -0.077221 -0.369308  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083814 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.015178 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549146  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549146  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [172]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [173]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           5
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [174]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [175]:
df.drop(['PassengerId','Name','Cabin'],axis=1,inplace=True)

In [176]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [177]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [178]:
df['Pclass'].unique()

array([ 3.,  1.,  2., nan])

In [179]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode() [0])
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Pclass']=df['Pclass'].fillna(df['Pclass'].mode() [0])

In [180]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [181]:
df.dtypes

Survived      int64
Pclass      float64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object

In [182]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [183]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Sex']=lab.fit_transform(df['Sex'])
df['Ticket']=lab.fit_transform(df['Ticket'])
df['Embarked']=lab.fit_transform(df['Embarked'])

In [184]:
df

Survived  Pclass  Sex        Age  SibSp  Parch  Ticket     Fare  Embarked
0           0     3.0    1  22.000000      1      0     523   7.2500         2
1           1     1.0    0  38.000000      1      0     596  71.2833         0
2           1     3.0    0  26.000000      0      0     669   7.9250         2
3           1     1.0    0  35.000000      1      0      49  53.1000         2
4           0     3.0    1  35.000000      0      0     472   8.0500         2
..        ...     ...  ...        ...    ...    ...     ...      ...       ...
886         0     2.0    1  27.000000      0      0     101  13.0000         2
887         1     1.0    0  19.000000      0      0      14  30.0000         2
888         0     3.0    0  29.699118      1      2     675  23.4500         2
889         1     1.0    1  26.000000      0      0       8  30.0000         0
890         0     3.0    1  32.000000      0      0     466   7.7500         1

[891 rows x 9 columns]

In [185]:
x=df.drop('Survived',axis=1)
x.ndim

2

In [186]:
y=df['Survived']
y.ndim

1

In [187]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [188]:
x_train

Pclass  Sex        Age  SibSp  Parch  Ticket     Fare  Embarked
857     1.0    1  51.000000      0      0      23  26.5500         2
52      1.0    0  49.000000      1      0     587  76.7292         0
386     3.0    1   1.000000      5      2     566  46.9000         2
124     1.0    1  54.000000      0      1     417  77.2875         2
578     3.0    0  29.699118      1      0     209  14.4583         0
..      ...  ...        ...    ...    ...     ...      ...       ...
835     1.0    0  39.000000      1      1     609  83.1583         0
192     3.0    0  19.000000      1      0     406   7.8542         2
629     3.0    1  29.699118      0      0     286   7.7333         1
559     3.0    0  36.000000      1      0     300  17.4000         2
684     2.0    1  60.000000      1      1     240  39.0000         2

[623 rows x 8 columns]

In [189]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [190]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [191]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[147,  21],
       [ 27,  73]])

In [192]:
score=accuracy_score(y_test,y_pred)
score

0.8208955223880597

In [193]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       168
           1       0.78      0.73      0.75       100

    accuracy                           0.82       268
   macro avg       0.81      0.80      0.81       268
weighted avg       0.82      0.82      0.82       268

